---
- name: clear out metrics nfs export
  file:
    state: absent
    path: '{{ openshift_hosted_metrics_storage_nfs_directory }}/{{ openshift_hosted_metrics_storage_volume_name }}'

- name: clear out metrics nfs export
  file:
    state: absent
    path: '{{ openshift_hosted_logging_storage_nfs_directory }}/{{ openshift_hosted_logging_storage_volume_name }}'
