---
- name: get server profiles
  oneview_server_profile_facts:
  register: sp
  delegate_to: localhost
  run_once: True

- name: get server hardwares
  oneview_server_hardware_facts:
  register: hw
  delegate_to: localhost
  run_once: True

- debug:
    msg: "server {{ item.name }} in bay {{ item.position }} has state {{ item.state }} with {{ item.memoryMb }} memory. it is a {{ item.shortModel }}. {{ item.processorCoreCount }} cores are spread across {{ item.processorCount }} at {{ item.processorSpeedMhz }} ({{ item.processorType }})."
  with_items:
  - "{{ hw.ansible_facts.server_hardwares }}"
  run_once: True

- name: set profile template to OCP-Master
  set_fact:
    server_profile_template: OCP-Master-Large
    deployment_plan: "{{ master_plan }}"
  when:
  - "'masters' in group_names"

- name: set profile template to OCP-Worker-Node
  set_fact:
    server_profile_template: OCP-Worker-Node-Large
    deployment_plan: "{{ worker_plan }}"
  when:
  - "'nodes' in group_names"

- name: set profile template to OCP-Node-Cns
  set_fact:
    server_profile_template: OCP-Node-CNS-Large
  when:
  - "'cns' in group_names"

- name: get profile facts
  oneview_server_profile_facts:
  register: profile_facts
  delegate_to: localhost

- debug:
    var: profile_facts
    verbosity: 2

- name: get os deployment plan facts
  oneview_os_deployment_plan_facts:
    name: "{{ deployment_plan }}"
  register: deployment_plan
  delegate_to: localhost

- name: set OS Deployment Plan URI
  set_fact:
    os_deployment_plan_uri:  "{{ deployment_plan.ansible_facts.os_deployment_plans.0.uri }}"

- name: get network facts
  oneview_ethernet_network_facts:
  delegate_to: localhost
  run_once: True
  register: eth_facts

- debug:
    var: eth_facts
    verbosity: 2

- name: set network uri
  set_fact:
    network_uri: "{{ item }}"
  with_items:  "{{ eth_facts|json_query(network_name_query) }}"
  vars:
    network_name_query:  "ansible_facts.ethernet_networks[?name=='{{ network_name }}'].uri"

- debug:
    var: network_uri
    verbosity: 2
