---
- name: power on server
  oneview_server_hardware:
    state: power_state_set
    data:
      name: "{{ hardware_name }}"
      powerStateData:
        powerState: "On"
        powerControl: "MomentaryPress"
  delegate_to: localhost
- debug:
    var: output
    verbosity: 2

- name: wait for server to become available
  local_action: wait_for port=22 host='{{ ansible_host }}' delay=30 timeout=3600
  tags:
  - poweron

#- name: wait a bit for the build scripts to run
#  pause:
#    minutes: 5
- name: ping
  ping:
